version: "3.9"
volumes:
  php-fpm-socket:
  psych-store:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: sample_app
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend
      - type: volume
        source: psych-store
        target: /root/.config/psych
        volume:
          nocopy: true

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: sample_nginx
    ports:
      - ${WEB_PORT}:80
      - "9000:9000"
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend

  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    container_name: sample_front
    volumes:
      - ./frontend:/var/www/nuxt
    ports:
      - ${FRONT_PORT}:3000
      - '24678:24678'